// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gkrvwybcvktjvprmgulp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdrcnZ3eWJjdmt0anZwcm1ndWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5NDg0NTEsImV4cCI6MjA2MzUyNDQ1MX0.L5wEBIGwdx99mNWVU7fTjIM3Xux1pd4EPjgCv-BpGtk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);